name: Run TCK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
       config: 
        - { name: 'JDBC', file: 'org.osgi.compatibility.jdbc/pom.xml' }
        - { name: 'JAX RS', file: 'org.osgi.compatibility.jaxrs/pom.xml' }
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: ${{ matrix.config.name }} TCK
      run: mvn -B clean verify --file ${{ matrix.config.file }} -Dbnd.testing.failure.ignore=true
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.config.name }}
        if-no-files-found: error
        path: '**/target/test-reports/**/*.xml'
